# Generated by Django 3.1.7 on 2021-03-28 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 20, 1, 44, 435245, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 20, 1, 44, 435209, tzinfo=utc), verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 20, 1, 44, 461859, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 20, 1, 44, 461835, tzinfo=utc), verbose_name='creado'),
        ),
    ]
