# Generated by Django 3.1.7 on 2021-03-28 21:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_auto_20210328_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='categoria',
            field=models.IntegerField(choices=[(0, 'inactivo'), (1, 'beneficiario'), (2, 'dirigente'), (3, 'resp.beneficiario'), (4, 'colaborador')], default=0),
        ),
        migrations.AlterField(
            model_name='familia',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 17, 27, 514151, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 17, 27, 514116, tzinfo=utc), verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 17, 27, 541318, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 17, 27, 541291, tzinfo=utc), verbose_name='creado'),
        ),
    ]
