# Generated by Django 3.1.7 on 2021-03-28 21:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_auto_20210328_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 42, 21, 340318, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 42, 21, 340288, tzinfo=utc), verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 42, 21, 367802, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 42, 21, 367776, tzinfo=utc), verbose_name='creado'),
        ),
    ]
