# Generated by Django 3.1.7 on 2021-03-28 21:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_auto_20210328_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 43, 14, 633500, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 43, 14, 633468, tzinfo=utc), verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 43, 14, 659996, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 43, 14, 659962, tzinfo=utc), verbose_name='creado'),
        ),
    ]
