# Generated by Django 3.1.7 on 2021-03-31 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_auto_20210328_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=400)),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
        ),
        migrations.AddField(
            model_name='familia',
            name='contacto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='familia',
            name='crm_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familia',
            name='direccion_calle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='familia',
            name='direccion_depto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='familia',
            name='direccion_localidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='familia',
            name='direccion_numero',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='familia',
            name='direccion_provincia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='socio',
            name='rama',
            field=models.IntegerField(choices=[(0, 'ninguna'), (1, 'manada'), (2, 'unidad scout'), (3, 'caminantes'), (4, 'rovers')], default=0),
        ),
        migrations.AlterField(
            model_name='socio',
            name='categoria',
            field=models.IntegerField(choices=[(0, 'inactivo'), (1, 'beneficiario'), (2, 'dirigente'), (3, 'recurso adulto'), (4, 'resp.beneficiario'), (5, 'colaborador')], default=0),
        ),
        migrations.AddField(
            model_name='familia',
            name='observaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socios.observaciones'),
        ),
    ]
