# Generated by Django 3.1.7 on 2021-04-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0008_auto_20210331_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='crm_id',
            field=models.IntegerField(unique=True),
        ),
    ]
