# Generated by Django 3.1.7 on 2021-04-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0009_auto_20210402_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='fecha_nacimiento'),
        ),
    ]
