# Generated by Django 3.1.7 on 2021-04-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0010_auto_20210406_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='dni',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
