# Generated by Django 3.1.7 on 2021-04-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0011_auto_20210410_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familia',
            options={'permissions': (('familia_crear', 'Agregar nueva familia'), ('familia_editar', 'Editar familia'), ('familia_borrar', 'Eliminar familia'), ('familia_ver', 'Ver informacion de familia'))},
        ),
        migrations.AlterModelOptions(
            name='observaciones',
            options={'permissions': (('familia_obs_crear', 'Agregar nueva observacion a una familia'), ('familia_obs_editar', 'Editar una observacion'), ('familia_obs_borrar', 'Eliminar una observacion'), ('familia_obs_ver', 'Ver una observacion'))},
        ),
        migrations.AlterModelOptions(
            name='socio',
            options={'permissions': (('socio_crear', 'Agregar nuevo socio a una familia'), ('socio_editar', 'Editar socio'), ('socio_borrar', 'Eliminar socio'), ('socio_ver', 'Ver informacion de un socio'))},
        ),
    ]
