# Generated by Django 3.1.7 on 2021-04-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0012_auto_20210411_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='socio',
            name='categoria',
            field=models.IntegerField(choices=[(-1, 'no_socio'), (0, 'inactivo'), (1, 'beneficiario'), (2, 'dirigente'), (3, 'recurso adulto'), (4, 'resp.beneficiario'), (5, 'colaborador')], default=0),
        ),
    ]
