# Generated by Django 3.1.7 on 2021-04-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0014_auto_20210424_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='crm_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
