# Generated by Django 3.1.7 on 2021-03-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaFamiliaAnual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimiento', models.DateTimeField(verbose_name='vencimiento')),
                ('importe', models.FloatField()),
                ('creado', models.DateTimeField(verbose_name='creado')),
                ('actualizado', models.DateTimeField(verbose_name='actualizado')),
            ],
        ),
    ]
