# Generated by Django 3.1.7 on 2021-03-28 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotapago',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 20, 1, 44, 474251, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='cuotapago',
            name='cobrado',
            field=models.DateField(verbose_name='cobrado'),
        ),
        migrations.AlterField(
            model_name='cuotapago',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 20, 1, 44, 474225, tzinfo=utc), verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='cuotasocialfamilia',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 20, 1, 44, 473537, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='cuotasocialfamilia',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 20, 1, 44, 473510, tzinfo=utc), verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='plandepago',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 20, 1, 44, 472806, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='plandepago',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 20, 1, 44, 472752, tzinfo=utc), verbose_name='creado'),
        ),
    ]
