# Generated by Django 3.1.7 on 2021-03-28 21:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0002_auto_20210328_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotapago',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 17, 27, 554317, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='cuotapago',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 17, 27, 554290, tzinfo=utc), verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='cuotasocialfamilia',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 17, 27, 553634, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='cuotasocialfamilia',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 17, 27, 553603, tzinfo=utc), verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='plandepago',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 17, 27, 552949, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='plandepago',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 17, 27, 552916, tzinfo=utc), verbose_name='creado'),
        ),
    ]
