# Generated by Django 3.1.7 on 2021-03-28 21:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0003_auto_20210328_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuotapago',
            name='cobrado',
        ),
        migrations.AlterField(
            model_name='cuotapago',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 42, 21, 380798, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='cuotapago',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 42, 21, 380765, tzinfo=utc), verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='cuotasocialfamilia',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 42, 21, 380076, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='cuotasocialfamilia',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 42, 21, 380050, tzinfo=utc), verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='plandepago',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 42, 21, 379392, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='plandepago',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 42, 21, 379354, tzinfo=utc), verbose_name='creado'),
        ),
    ]
