# Generated by Django 3.1.7 on 2021-03-28 21:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0004_auto_20210328_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotapago',
            name='importe',
            field=models.FloatField(default=0.0, verbose_name='cobrado'),
        ),
        migrations.AlterField(
            model_name='cuotapago',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 43, 14, 672803, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='cuotapago',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 43, 14, 672777, tzinfo=utc), verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='cuotasocialfamilia',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 43, 14, 672116, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='cuotasocialfamilia',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 43, 14, 672079, tzinfo=utc), verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='plandepago',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 43, 14, 671455, tzinfo=utc), verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='plandepago',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 21, 43, 14, 671420, tzinfo=utc), verbose_name='creado'),
        ),
    ]
