# Generated by Django 3.1.7 on 2021-03-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0005_auto_20210328_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotapago',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='cuotapago',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='cuotasocialfamilia',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='cuotasocialfamilia',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='plandepago',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='plandepago',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
    ]
