# Generated by Django 3.1.7 on 2021-03-31 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0006_auto_20210328_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotapago',
            name='fecha_cobro',
            field=models.DateField(default=datetime.date.today, verbose_name='fecha_cobro'),
        ),
    ]
