# Generated by Django 3.1.7 on 2021-04-01 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0007_cuotapago_fecha_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotapago',
            name='aplica_pago_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuotas.plandepago'),
        ),
    ]
