# Generated by Django 3.1.7 on 2021-04-01 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0009_auto_20210401_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuotapago',
            name='aplica_cuota',
        ),
    ]
