# Generated by Django 3.1.7 on 2021-04-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0010_remove_cuotapago_aplica_cuota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuotapago',
            options={'permissions': (('plan_cuota_crear', 'Agregar nuevas cuotas de un plan a familia'), ('plan_cuota_editar', 'Editar cuotas de un plan a familia'), ('plan_cuota_borrar', 'Eliminar cuotas de un plan a familia'), ('plan_cuota_ver', 'Ver detalle de cuotas del plan a familia'))},
        ),
        migrations.AlterModelOptions(
            name='plandepago',
            options={'permissions': (('planpago_crear', 'Agregar nuevo plan de pago'), ('planpago_editar', 'Editar plan de pago'), ('planpagos_borrar', 'Eliminar un plan de pago'), ('planpago_ver', 'Ver detalle de plan de pago'))},
        ),
    ]
