# Generated by Django 3.1.7 on 2021-04-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0013_cuotasocialfamilia_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotapago',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
