# Generated by Django 3.1.7 on 2021-04-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0014_cuotapago_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandepago',
            name='orden',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='plandepago',
            name='plan_default',
            field=models.BooleanField(default=False),
        ),
    ]
