# Generated by Django 3.1.7 on 2021-04-29 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0015_auto_20210429_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotapago',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator('0.01')], verbose_name='cobrado'),
        ),
    ]
