# Generated by Django 3.1.7 on 2021-04-29 22:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0016_auto_20210429_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotapago',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('1.0'))], verbose_name='cobrado'),
        ),
    ]
