# Generated by Django 3.2 on 2021-05-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0017_auto_20210429_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuotasocialfamilia',
            options={'permissions': (('cuota_crear', 'Agregar nuevo plan de pago'), ('cuota_editar', 'Editar plan de pago'), ('cuota_borrar', 'Eliminar un plan de pago'), ('cuota_ver', 'Ver detalle de plan de pago'))},
        ),
    ]
