# Generated by Django 3.2 on 2021-05-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0019_alter_cuotapago_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuotasocialfamilia',
            options={'permissions': (('cuota_crear', 'Agregar cuotas'), ('cuota_editar', 'Editar cuotas'), ('cuota_borrar', 'Eliminar cuotas'), ('cuota_ver', 'Ver detalle de cuotas'))},
        ),
    ]
