# Generated by Django 3.2.5 on 2021-07-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0021_alter_cuotapago_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaMedioDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_id', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=300)),
                ('disponible', models.BooleanField(default=False)),
            ],
        ),
    ]
