# Generated by Django 3.2.5 on 2021-07-11 23:44

from django.db import migrations
from cuotas.models import CuotaMedioDePago 

def registro_inicial_de_medios_de_pago(apps, schema_editor):
    '''Genero el registro inicial minimo de Cobro contado'''
    efectivo = CuotaMedioDePago.objects.create(medio_id="EF",descripcion="Pago en efectivo",disponible=True)
    efectivo.save()

    mercado_pago = CuotaMedioDePago.objects.create(medio_id="MP",descripcion="Transeferencia entre cuentras Mercado Pago",disponible=True)
    mercado_pago.save()
    


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0022_cuotamediodepago'),
    ]

    operations = [
        migrations.RunPython(registro_inicial_de_medios_de_pago)
    ]
