# Generated by Django 3.2.5 on 2021-08-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0024_auto_20210712_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotapago',
            name='comprobante',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
