# Generated by Django 3.2 on 2022-03-14 03:42

import cuotas.models
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0025_cuotapago_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotapago',
            name='hash',
            field=models.UUIDField(default=uuid.uuid4, null=False),
        ),
    ]
