# Generated by Django 3.2 on 2022-03-14 03:42

import cuotas.models
from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('cuotas', 'CuotaPago')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        print(f"UUID:{row.uuid}")
        row.save(update_fields=['hash'])

class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0026_cuotapago_hash'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]

# La migracion no genera UUIDs unicos, se debe correr esto manual "python manager shell" para solucionarlo por consola
# >>> from cuotas.models import CuotaPago
# >>> import uuid
# >>> all_cuotas = CuotaPago.objet.all()
# >>> for cuota in all_cuotas:
# ...   cuota.hash = uuid.uuid4()
# ...   cuota.save(update_fields=['hash'])