# Generated by Django 3.1.7 on 2021-03-27 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia_crm_id', models.CharField(max_length=50)),
                ('creado', models.DateTimeField(verbose_name='creado')),
                ('actualizado', models.DateTimeField(verbose_name='actualizado')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha_nacimiento')),
                ('creado', models.DateTimeField(verbose_name='creado')),
                ('actualizado', models.DateTimeField(verbose_name='actualizado')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.familia')),
            ],
        ),
    ]
